# day 12

# use list to create array

In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# use tuple to create numpy array

In [4]:
arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# dimension in array

#zero-d array

In [9]:
arr = np.array(5)
print(arr)
print(type(arr))
print(arr.ndim)



5
<class 'numpy.ndarray'>
0


1 d array

In [10]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


2 d array

In [11]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(type(arr))
print(arr.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>
2


In [12]:
arr = np.array([[1,2.5,3.6,4.9,5],[6,7,8,9,10]])
print(arr)
print(type(arr))
print(arr.ndim)

[[ 1.   2.5  3.6  4.9  5. ]
 [ 6.   7.   8.   9.  10. ]]
<class 'numpy.ndarray'>
2


3 d array

In [13]:
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)
print(type(arr))
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>
3


# create an array with 5 dimensions and verify that it has 5 dimensions

In [19]:
arr = np.array([1,2,3,4,5], ndmin=5)
# arr = np.array([[[[[1,2,3,4,5]]]]])
print(arr)
print(arr.ndim)

[[[[[1 2 3 4 5]]]]]
5


# numpy array indexing

# accessing 1D array

In [23]:
#get first element 
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[0])

1


In [24]:
#get third, sixth and eight element and add them
a = np.array([1,2,3,4,5,6,7,8,9,10])
print("third" , a[2])
print("sixth" , a[5])
print("eight" , a[7])
print("sum" , a[2] + a[5] + a[7])


third 3
sixth 6
eight 8
sum 17


# accessing 2D array

In [31]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0, 1])
print(arr[0, 3])
print(arr[1, 0])

2
4
6


access 1st row and last eletement and add them

In [32]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0, 0])
print(arr[1, 4])
print("sum" , arr[0, 0] + arr[1, 4])

1
10
sum 11


# accessing 3D array

In [36]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[1,0,0])
print(arr[1,1,0])
print(arr[0,0,2])

7
10
3


# day 13

# slicing in 1D

In [44]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[1:5])
print(arr[::3]) #skip two then print

[2 3 4 5]
[ 1  4  7 10]


# slicing in 2D

In [39]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,1:4])

[2 3 4]


# slicing in 3D

In [45]:
arr = np.array([[[1,2,3,8,15,13],[4,5,6,52,85,41]],[[7,8,9,10,6,99],[10,11,12,11,16,17]]])
print(arr[1,1,2:5])
print(arr[1,0,1:4])

[12 11 16]
[ 8  9 10]


# datatypes in numpy

i - integer
b- boolean
u-unsigned integer
f-float
c-complex float
m-timedelta
M-datetime
O-object
S-string
U-unicode string
V- fixed chunckof memory for other type (void)

# check datatype of array

In [46]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr.dtype)

int32


# create arrays with a defined data type

In [48]:
arr = np.array([1,2,3,4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


# create an array with data types 4 bytes integer

In [49]:
arr = np.array([1,2,3,4],dtype = 'i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


# numpy array shape

the shape of an array is the number of elements in each dimension

# print the shape of a 2D array

In [53]:
arr  = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


# print the shape of a 3D array

In [55]:
arr  = np.array([[[1,2,3,4],[5,6,7,8],[10,11,12,13]]])
print(arr.shape)

(1, 3, 4)


# join numpy arrays

# concatenation for 1D

In [60]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6 7 8]


# concatenate for 2D

In [11]:
arr1 = np.array([[1,2,3],[4,5,6]])  
arr2 = np.array([[7,8,9],[10,11,12]]) 
# have two axis i.e 0 and 1
# output along axis 1
arr = np.concatenate((arr1,arr2) , axis=1)
print(arr)
# output along axis 0 
print()
arr = np.concatenate((arr1,arr2) , axis=0)
print(arr)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# splitting numpy arrays

# splitting array in 3 parts

In [12]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


# splittiing array in 4 parts

In [14]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


# ravel and flatten

convert multidimensional array into 1D array

In [20]:
m = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(m)
print(m.ndim)

# convert to 1D
n = m.ravel()
print("new dimension with raven is \n ",n)

# convert to 1D
n = m.flatten()
print("new dimension with flatten is \n ",n)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
new dimension with raven is 
  [1 2 3 4 5 6 7 8 9]
new dimension with flatten is 
  [1 2 3 4 5 6 7 8 9]


In [22]:
c = np.array([[[[1,2,3],[4,5,6],[7,8,9]]]])
print(c)
print(c.ndim)

d = c.ravel()
print(d)
print(d.ndim)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]
4
[1 2 3 4 5 6 7 8 9]
1


# unique function

In [23]:
k = np.array([12,1,4,6,7,9,4,5,22,33,7,6,9,1,2,12])
print(k)
x = np.unique(k)
print(x)

[12  1  4  6  7  9  4  5 22 33  7  6  9  1  2 12]
[ 1  2  4  5  6  7  9 12 22 33]


In [24]:
# also to find index position of unique elements
k = np.array([12,1,4,6,7,9,4,5,22,33,7,6,9,1,2,12])
print(k)
x = np.unique(k, return_index = True)
print(x)

[12  1  4  6  7  9  4  5 22 33  7  6  9  1  2 12]
(array([ 1,  2,  4,  5,  6,  7,  9, 12, 22, 33]), array([ 1, 14,  2,  7,  3,  4,  5,  0,  8,  9], dtype=int64))


In [26]:
# also to find repetition of unique elements
k = np.array([12,1,4,6,7,9,4,5,22,33,7,6,9,1,2,12])
print(k)
x = np.unique(k, return_index = True, return_counts = True)
print(x)

[12  1  4  6  7  9  4  5 22 33  7  6  9  1  2 12]
(array([ 1,  2,  4,  5,  6,  7,  9, 12, 22, 33]), array([ 1, 14,  2,  7,  3,  4,  5,  0,  8,  9], dtype=int64), array([2, 1, 2, 1, 2, 2, 2, 2, 1, 1], dtype=int64))


# delete

# 1D array

In [29]:
a = np.array([12,13,14,15])
d = np.delete(a,[1])
print(d)

[12 14 15]


# 2D array

In [36]:
x = np.array([[2,7,9,6,8],[4,5,7,1,2],[50,0,65,6,7]])
print(x)
print()
d = np.delete(x,1,0)
print(d)
print()

d = np.delete(x,0,0)
print(d)

[[ 2  7  9  6  8]
 [ 4  5  7  1  2]
 [50  0 65  6  7]]

[[ 2  7  9  6  8]
 [50  0 65  6  7]]

[[ 4  5  7  1  2]
 [50  0 65  6  7]]
